### ISSUE TITLE
dropbtn

### ISSUE THREAD

**Issue by dinumifonseka** [dinumifonseka/Hospital-Web-#3]
meke mata one 

 medical and surgical services vala 
                       Centrl of exelence
                                  blood cancer
                                   emegency services
                                   paediatric services
                       surgical survices
                                   general surgery
                                    ..................
                                    ,.................
                       generasl servuces

onna ohoma ekak athle ekak gahanna

**Comment by DhanujaRehan** [comment]
haduwa
